services:
  # ---------- client ----------
  client:
    build: client
    restart: unless-stopped
    volumes:
      - ./client/src:/app/src
    ports: [ "5173:5173" ]
    depends_on: [ server ]

  # ---------- postgres ----------
  database:
    container_name: wsd_project_database 
    image: postgres:17.0
    restart: unless-stopped
    env_file:
      - project.env

  # ---------- flyway ----------
  database-migrations:
    image: flyway/flyway:10
    env_file:
      - project.env
    depends_on: [ database ]
    volumes:
      - ./database-migrations:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

  # ---------- e2e ----------
  e2e-tests:
    entrypoint: "/bin/true"
    build: e2e-tests
    network_mode: host
    depends_on: [ client ]
    volumes:
      - ./e2e-tests/tests:/app/tests

  # ---------- api ----------
  server:
    build: server
    restart: unless-stopped
    volumes:
      - ./server:/app
    ports: [ "8000:8000" ]
    env_file:
      - project.env
    depends_on: [ database ]
